fix  cargo error
error: failed to parse manifest at `/home/azureuser/ZEN/zen-arkworks/Cargo.toml`

Caused by:
  key `branch` is ignored for dependency (ark-crypto-primitives).